### PR TITLE
[#96562016] Create some basic smoke tests

### PR DESCRIPTION
**Pull request by keymon**
[#96562016 Create some basic smoke tests](https://www.pivotaltracker.com/n/projects/1275640/stories/96562016)

**Context**

This PR prepares the jenkins server and setups the jobs to run the smoke tests implemented [in the related tsuru-ansible PR](https://github.com/alphagov/tsuru-ansible/pull/93)

**How this PR should be reviewed**
1. If [this tsuru-ansible PR](https://github.com/alphagov/tsuru-ansible/pull/93) is not merged, you must revert [this commit](a1ee8b6515dc23b6a27277b7c15973933815f633) to point the jobs to the `tsuru-testing` branch.
2. Bring up a vagrant jenkins as described in README.md. `make vagrant-up` uses `DEPLOY_ENV=development` by default, but if you want point it to your own tsuru environment with `DEPLOY_ENV=env-name vagrant up`. To reprovision ansible: `DEPLOY_ENV=env-name vagrant provision`. 
3. Connect to jenkins on vagrant and run a the jobs.

**How is this PR implemented?**

In order to implement this logic, we have:
- Added a new galaxy role `rvm_io.rvm1-ruby` which installs RVM, in order to install and switch the required version of ruby: 2.2.2
- We install the tsuru client on the server.
- Added new credentials to the vault for the tsuru platform.
- Added the job definitions to run the tests on both platforms: aws and gce

**Who should review this PR**

Anybody in the team except @saliceti or @keymon

### CODE REVIEW

**Comment by mtekel** [comment]
How do you handle tsuru concurrency?
- when you merge tsuru-terraform, jenkins runs that job
- which in turn triggers two concurrent ansible jobs (GCE and AWS)
- which would trigger two concurrent smoketest jobs

But tsuru client can be logged only into one environment at a time. So it would happen that the second job would simply log in to second environment and break the 1st one... The login information (token and the selected target) are stored in the home directory. I am not sure if you can change that while running (inside ruby) and what all it would affect...

EDIT: I see this is being handled by [temp homedirs](https://github.com/alphagov/tsuru-ansible/blob/tsuru-testing/spec/endtoend/endtoend_spec.rb#L9)

**Comment by keymon** [comment]
@mtekel Yes, that is the idea of the temp homedirs. The tests can run in parallel if they point to different target platforms. Not so true for the same target, as the target keeps some state. Maybe we can workaround it and allow concurrency by randomising the name of the different resources: app, db instance, etc. But, that is for a different PR ;)

Other problem with this PR is that it can happen that the smoke tests run at the same time than ansible or terraform, which can make the test file. We need to use a jenkins lock plugin for this, but again we decided do it in a different PR if it really causes trouble.

**Comment by keymon** [comment]
Updated the repo to use `make` to run the tests, instead of calling `rake` directly

**Comment by mtekel** [comment]
Works fine.

**Pull request merged**
