### PR TITLE
[#103903920] Cloud Foundry phoenix jobs

### PR DESCRIPTION
**Pull request by saliceti**
# What

We are now saving time by reusing our environments, but we still need to test building an environment from scratch. This PR adds Ansible templates to generate the jobs in Jenkins.

We manage passwords with `paas-pass` so this had to be installed on Jenkins. And we need SSH keys to access the credentials repository so the management of these keys has been added.

Terraform has been upgraded to 0.6.3 because the syntax in CF terraform code requires it.

This also includes some optimisations to save time building and running Jenkins.

Related PRs:
- https://github.com/alphagov/cf-terraform/pull/47
- https://github.gds/multicloudpaas/credentials/pull/18
# How to review
- Ideally merge the first 2 PRs
- Run `vagrant up`
- Open jenkins on https://127.0.0.1:8443
- Start job `ci-cf-deploy-phoenix-aws` or `ci-cf-deploy-phoenix-gce`
- It should build a new environment, run smoke tests on it, and destroy it
- Wait until 7am until it starts automatically
# Who can review

Anyone but @saliceti, @jimconner , @Jonty

### CODE REVIEW

**Comment by dcarley** [comment]
I haven't had a chance to review this properly yet, but I did notice that the first 4 commits on this branch probably shouldn't be in this PR because they're already on `master`. Any idea how that happened? Does it need a rebase?

**Comment by saliceti** [comment]
Thanks, I have rebased it against master, looks ok now.

**Comment by Jonty** [comment]
FWIW I'm pretty sure that happened by accident when we were squashing commits on the branch.

**Comment by dcarley** [comment]
Still running but seems fine so far.

In kick-off we talked about having two CI environments which are:
1. built from scratch and destroyed every morning
2. continually running and giving us feedback from merges to master

The first is covered by this PR but not the second. Is that intentional?

I'm unsure about the name "phoenix" because I'm not sure it clearly describes the purpose to newcomers. Interested in other peoples thoughts, but it's not a blocker to merging.

**Comment by saliceti** [comment]
I believe we agreed to deliver only the first one in this story, and the second one would be delivered later.

**Comment by annashipman** [comment]
This is great, but I agree with Dan about the name 'phoenix'; it didn't make it clear to me what that was for. Something more descriptive might be better, like 'daily build' or something along those lines.

**Comment by dcarley** [comment]
> I believe we agreed to deliver only the first one in this story, and the second one would be delivered later.

We didn't write it down, so all bets are off. We (probably Brett and I) should make sure that we summarise kick-offs so that we're clear about such details. I'll create a new story for the 2nd part.

Could you change the name of the jobs? Then this'll be good to go.

**Comment by saliceti** [comment]
OK changed it to "daily-build".

**Comment by dcarley** [comment]
@saliceti @jimconner or @Jonty: Could you confirm that my last two commits on this PR are sane?

**Comment by saliceti** [comment]
Tested successfully with new password-store URL.

**Comment by dcarley** [comment]
I haven't merged this yet because I'm still trying to delete the environment that I created (which uses the default name).

**Comment by dcarley** [comment]
Deployed.

**Pull request merged**
